# Generated by Django 2.2.13 on 2020-08-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200820_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_manage_authors', 'Create, update, delete authors.'),)},
        ),
    ]
