# Generated by Django 2.2.13 on 2020-08-22 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200821_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_manage_books', 'Create, update, delete book records.'),)},
        ),
    ]
